# CMake Toolchain File for Yocto SDK Cross-Compilation
# Target: NXP i.mX8M Plus (aarch64)
# Usage: cmake -DCMAKE_TOOLCHAIN_FILE=yocto-toolchain.cmake ..

# This file is auto-generated by Yocto SDK environment setup script
# Source the SDK environment file before running CMake:
#   source /path/to/sdk/environment-setup-aarch64-poky-linux

# Target system information
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 6.6.52)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Cross-compiler prefix (aarch64-poky-linux-gcc)
set(CMAKE_C_COMPILER aarch64-poky-linux-gcc)
set(CMAKE_CXX_COMPILER aarch64-poky-linux-g++)

# SDK sysroot (set by Yocto SDK environment)
if(NOT DEFINED CMAKE_SYSROOT)
    set(CMAKE_SYSROOT ${OECORE_NATIVE_SYSROOT})
endif()

# Find root path for libraries and headers
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

# Search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Search for libraries and headers in the target directories only
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Adjust PKG_CONFIG to search in sysroot
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})

# Compiler flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --sysroot=${CMAKE_SYSROOT}")

# Linker flags
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,-rpath-link,${CMAKE_SYSROOT}/usr/lib")

# Library search paths
link_directories(${CMAKE_SYSROOT}/usr/lib)

# Additional architecture-specific settings
set(CMAKE_LIBRARY_ARCHITECTURE aarch64-poky-linux)

# Qt configuration (if needed)
# set(QT_COMPILER_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_CXX_FLAGS}")
