namespace CodeGenerator.Core.Generators;

using System;
using System.IO;
using System.Threading.Tasks;
using CodeGenerator.Core.Models;

/// <summary>
/// C/C++ header file generator for FPGA register map definitions.
/// Generates fpga_registers.h with addresses, bit fields, and documentation.
/// SPEC-TOOLS-001 REQ-TOOLS-011
/// </summary>
public class CHeaderGenerator
{
    private const string AutoGenComment = "// AUTO-GENERATED - DO NOT EDIT";

    /// <summary>
    /// Generate fpga_registers.h with register addresses and bit field macros.
    /// </summary>
    public async Task GenerateFpgaRegistersAsync(DetectorConfig config, string outputPath)
    {
        var content = $@"{AutoGenComment}
// Generated by CodeGenerator CLI tool
// Source: detector_config.yaml
// Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

#ifndef FPGA_REGISTERS_H
#define FPGA_REGISTERS_H

#include <stdint.h>

#ifdef __cplusplus
extern ""C"" {{
#endif

/**
 * Register map for FPGA-SoC SPI communication.
 * All registers are 32-bit aligned.
 */

// Register base addresses
#define FPGA_REG_PANEL_BASE        0x0000
#define FPGA_REG_TIMING_BASE       0x0100
#define FPGA_REG_BUFFER_BASE       0x0200
#define FPGA_REG_CSI2_BASE         0x0300
#define FPGA_REG_PROTECTION_BASE   0x0400
#define FPGA_REG_STATUS_BASE       0x0500

// Panel configuration registers
#define FPGA_REG_PANEL_ROWS        (FPGA_REG_PANEL_BASE + 0x00)  // RO, uint16_t
#define FPGA_REG_PANEL_COLS        (FPGA_REG_PANEL_BASE + 0x04)  // RO, uint16_t
#define FPGA_REG_PIXEL_PITCH       (FPGA_REG_PANEL_BASE + 0x08)  // RO, uint16_t (um)
#define FPGA_REG_BIT_DEPTH         (FPGA_REG_PANEL_BASE + 0x0C)  // RO, uint8_t

// Timing registers (microseconds)
#define FPGA_REG_GATE_ON_US        (FPGA_REG_TIMING_BASE + 0x00)  // RW, float
#define FPGA_REG_GATE_OFF_US       (FPGA_REG_TIMING_BASE + 0x04)  // RW, float
#define FPGA_REG_ROIC_SETTLE_US    (FPGA_REG_TIMING_BASE + 0x08)  // RW, float
#define FPGA_REG_ADC_CONV_US       (FPGA_REG_TIMING_BASE + 0x0C)  // RW, float

// Line buffer registers
#define FPGA_REG_BUFFER_DEPTH      (FPGA_REG_BUFFER_BASE + 0x00)  // RO, uint8_t
#define FPGA_REG_BRAM_WIDTH        (FPGA_REG_BUFFER_BASE + 0x04)  // RO, uint8_t

// CSI-2 registers
#define FPGA_REG_CSI2_LANE_COUNT   (FPGA_REG_CSI2_BASE + 0x00)   // RO, uint8_t
#define FPGA_REG_CSI2_DATA_TYPE    (FPGA_REG_CSI2_BASE + 0x04)   // RO, uint8_t (0x2C=RAW16, 0x2D=RAW14)
#define FPGA_REG_CSI2_VC           (FPGA_REG_CSI2_BASE + 0x08)   // RO, uint8_t
#define FPGA_REG_CSI2_LANE_SPEED   (FPGA_REG_CSI2_BASE + 0x0C)   // RO, uint32_t (Mbps)

// Protection registers
#define FPGA_REG_TIMEOUT_MS        (FPGA_REG_PROTECTION_BASE + 0x00)  // RW, uint32_t
#define FPGA_REG_OVEREXPOSE_THRESH (FPGA_REG_PROTECTION_BASE + 0x04)  // RW, uint16_t
#define FPGA_REG_OVERFLOW_ACTION   (FPGA_REG_PROTECTION_BASE + 0x08)  // RW, uint8_t (0=stop,1=drop,2=overwrite)

// Status registers
#define FPGA_REG_SCAN_MODE         (FPGA_REG_STATUS_BASE + 0x00)   // RO, uint8_t
#define FPGA_REG_FRAME_COUNT       (FPGA_REG_STATUS_BASE + 0x04)   // RO, uint32_t
#define FPGA_REG_ERROR_FLAGS       (FPGA_REG_STATUS_BASE + 0x08)   // RO, uint32_t

// Bit field definitions for error flags
#define FPGA_ERR_OVERRUN           (1U << 0)  // Line buffer overrun
#define FPGA_ERR_TIMEOUT           (1U << 1)  // Watchdog timeout
#define FPGA_ERR_OVEREXPOSURE      (1U << 2)  // Overexposure detected
#define FPGA_ERR_CSI2_FIFO         (1U << 3)  // CSI-2 FIFO overflow

// Scan mode values
#define FPGA_SCAN_MODE_IDLE        0x00
#define FPGA_SCAN_MODE_SINGLE      0x01
#define FPGA_SCAN_MODE_CONTINUOUS  0x02

/**
 * FPGA register map structure for direct memory access.
 * Packed to ensure correct memory layout.
 */
#pragma pack(push, 1)
typedef struct {{
    uint32_t panel_rows;
    uint32_t panel_cols;
    uint32_t pixel_pitch_um;
    uint32_t bit_depth;
    float    gate_on_us;
    float    gate_off_us;
    float    roic_settle_us;
    float    adc_conv_us;
    uint32_t buffer_depth;
    uint32_t bram_width_bits;
    uint32_t csi2_lane_count;
    uint32_t csi2_data_type;
    uint32_t csi2_virtual_channel;
    uint32_t csi2_lane_speed_mbps;
    uint32_t timeout_ms;
    uint32_t overexposure_threshold;
    uint32_t overflow_action;
}} fpga_register_map_t;
#pragma pack(pop)

// Default configuration values (from detector_config.yaml)
#define FPGA_DEFAULT_PANEL_ROWS        {config.Panel.Rows}
#define FPGA_DEFAULT_PANEL_COLS        {config.Panel.Cols}
#define FPGA_DEFAULT_PIXEL_PITCH_UM    {config.Panel.PixelPitchUm}
#define FPGA_DEFAULT_BIT_DEPTH         {config.Panel.BitDepth}
#define FPGA_DEFAULT_GATE_ON_US        {config.Fpga.Timing.GateOnUs:F1}f
#define FPGA_DEFAULT_GATE_OFF_US       {config.Fpga.Timing.GateOffUs:F1}f
#define FPGA_DEFAULT_ROIC_SETTLE_US    {config.Fpga.Timing.RoicSettleUs:F1}f
#define FPGA_DEFAULT_ADC_CONV_US       {config.Fpga.Timing.AdcConvUs:F1}f
#define FPGA_DEFAULT_BUFFER_DEPTH      {config.Fpga.LineBuffer.DepthLines}
#define FPGA_DEFAULT_BRAM_WIDTH        {config.Fpga.LineBuffer.BramWidthBits}
#define FPGA_DEFAULT_CSI2_LANE_COUNT   {config.Fpga.DataInterface.Csi2.LaneCount}
#define FPGA_DEFAULT_CSI2_DATA_TYPE    {GetCsi2DataTypeHex(config.Fpga.DataInterface.Csi2.DataType)}
#define FPGA_DEFAULT_CSI2_VC           {config.Fpga.DataInterface.Csi2.VirtualChannel}
#define FPGA_DEFAULT_CSI2_LANE_SPEED   {config.Fpga.DataInterface.Csi2.LaneSpeedMbps}

#ifdef __cplusplus
}}
#endif

#endif // FPGA_REGISTERS_H
";

        await File.WriteAllTextAsync(outputPath, content);
    }

    /// <summary>
    /// Generate all C header files to the specified output directory.
    /// </summary>
    public async Task GenerateAllAsync(DetectorConfig config, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        await GenerateFpgaRegistersAsync(config, Path.Combine(outputDir, "fpga_registers.h"));
    }

    private static string GetCsi2DataTypeHex(string dataType)
    {
        return dataType == "RAW16" ? "0x2C" : "0x2D";
    }
}
