namespace CodeGenerator.Core.Generators;

using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using CodeGenerator.Core.Models;

/// <summary>
/// C# SDK class skeleton generator.
/// Generates DetectorConfig.cs and FrameHeader.cs with correct defaults and struct layout.
/// SPEC-TOOLS-001 REQ-TOOLS-012
/// </summary>
public class CSharpGenerator
{
    private const string AutoGenComment = "// AUTO-GENERATED - DO NOT EDIT";

    /// <summary>
    /// Generate DetectorConfig.g.cs with default values.
    /// </summary>
    public async Task GenerateDetectorConfigAsync(DetectorConfig config, string outputPath)
    {
        var content = $@"{AutoGenComment}
// Generated by CodeGenerator CLI tool
// Source: detector_config.yaml
// Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

namespace SystemEmulSim.Sdk;

/// <summary>
/// Detector configuration default values.
/// Extracted from detector_config.yaml.
/// </summary>
public static partial class DetectorConfig
{{
    // Panel configuration
    public const int DefaultRows = {config.Panel.Rows};
    public const int DefaultCols = {config.Panel.Cols};
    public const double DefaultPixelPitchUm = {config.Panel.PixelPitchUm};
    public const int DefaultBitDepth = {config.Panel.BitDepth};

    // FPGA timing (microseconds)
    public const double DefaultGateOnUs = {config.Fpga.Timing.GateOnUs};
    public const double DefaultGateOffUs = {config.Fpga.Timing.GateOffUs};
    public const double DefaultRoicSettleUs = {config.Fpga.Timing.RoicSettleUs};
    public const double DefaultAdcConvUs = {config.Fpga.Timing.AdcConvUs};

    // Line buffer configuration
    public const int DefaultBufferDepthLines = {config.Fpga.LineBuffer.DepthLines};
    public const int DefaultBramWidthBits = {config.Fpga.LineBuffer.BramWidthBits};

    // CSI-2 configuration
    public const int DefaultCsi2LaneCount = {config.Fpga.DataInterface.Csi2.LaneCount};
    public const string DefaultCsi2DataType = ""{config.Fpga.DataInterface.Csi2.DataType}"";
    public const int DefaultCsi2VirtualChannel = {config.Fpga.DataInterface.Csi2.VirtualChannel};
    public const int DefaultCsi2LaneSpeedMbps = {config.Fpga.DataInterface.Csi2.LaneSpeedMbps};

    // SPI configuration
    public const int DefaultSpiClockHz = {config.Fpga.Spi.ClockHz};
    public const int DefaultSpiMode = {config.Fpga.Spi.Mode};
    public const int DefaultSpiWordSizeBits = {config.Fpga.Spi.WordSizeBits};

    // Controller configuration
    public const string DefaultPlatform = ""{config.Controller.Platform}"";

    // Ethernet configuration
    public const string DefaultEthernetSpeed = ""{config.Controller.Ethernet.Speed}"";
    public const string DefaultEthernetProtocol = ""{config.Controller.Ethernet.Protocol}"";
    public const int DefaultEthernetPort = {config.Controller.Ethernet.Port};
    public const int DefaultEthernetMtu = {config.Controller.Ethernet.Mtu};
    public const int DefaultUdpPayloadSize = {config.Controller.Ethernet.PayloadSize};

    // Frame buffer configuration
    public const int DefaultFrameBufferCount = {config.Controller.FrameBuffer?.Count ?? 4};
    public const int DefaultFrameBufferAllocationMb = {config.Controller.FrameBuffer?.AllocationMb ?? 128};

    // Host storage configuration
    public const string DefaultStorageFormat = ""{config.Host.Storage.Format}"";
    public const string DefaultStoragePath = ""{config.Host.Storage.Path}"";
    public const string DefaultStorageCompression = ""{config.Host.Storage.Compression}"";

    // Display configuration
    public const int DefaultDisplayFps = {config.Host.Display.Fps};
    public const string DefaultDisplayColorMap = ""{config.Host.Display.ColorMap}"";
    public const double DefaultDisplayWindowScale = {config.Host.Display.WindowScale};

    // Network configuration
    public const int DefaultReceiveBufferMb = {config.Host.Network?.ReceiveBufferMb ?? 64};
    public const int DefaultReceiveThreads = {config.Host.Network?.ReceiveThreads ?? 2};
    public const int DefaultPacketTimeoutMs = {config.Host.Network?.PacketTimeoutMs ?? 1000};

    /// <summary>
    /// Calculate frame size in bytes.
    /// </summary>
    public static int CalculateFrameSizeBytes(int rows, int cols, int bitDepth)
    {{
        return rows * cols * ((bitDepth + 7) / 8);
    }}

    /// <summary>
    /// Calculate frame size in bytes using default configuration.
    /// </summary>
    public static int CalculateDefaultFrameSizeBytes()
    {{
        return CalculateFrameSizeBytes(DefaultRows, DefaultCols, DefaultBitDepth);
    }}

    /// <summary>
    /// Calculate packets per frame for UDP transmission.
    /// </summary>
    public static int CalculatePacketsPerFrame(int frameSizeBytes, int payloadSize)
    {{
        return (frameSizeBytes + payloadSize - 1) / payloadSize;
    }}

    /// <summary>
    /// Calculate packets per frame using default configuration.
    /// </summary>
    public static int CalculateDefaultPacketsPerFrame()
    {{
        return CalculatePacketsPerFrame(CalculateDefaultFrameSizeBytes(), DefaultUdpPayloadSize);
    }}
}}
";

        await File.WriteAllTextAsync(outputPath, content);
    }

    /// <summary>
    /// Generate FrameHeader.g.cs with struct layout matching protocol.
    /// </summary>
    public async Task GenerateFrameHeaderAsync(DetectorConfig config, string outputPath)
    {
        var content = $@"{AutoGenComment}
// Generated by CodeGenerator CLI tool
// Source: detector_config.yaml
// Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

using System.Runtime.InteropServices;

namespace SystemEmulSim.Sdk;

/// <summary>
/// Frame header structure for network protocol.
/// Layout must match FPGA and SoC firmware definitions.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct FrameHeader
{{
    // Magic number for frame synchronization (0xAA55AA55)
    public uint MagicNumber;

    // Protocol version (0x01)
    public byte ProtocolVersion;

    // Frame flags (bit 0: start of frame, bit 1: end of frame)
    public byte Flags;

    // Frame number (rolling counter)
    public uint FrameNumber;

    // Image dimensions
    public ushort Rows;
    public ushort Cols;

    // Bit depth (14 or 16)
    public ushort BitDepth;

    // Reserved for future use
    private ushort _reserved1;

    // Timestamp in microseconds since epoch
    public ulong TimestampUs;

    // Frame size in bytes
    public uint FrameSizeBytes;

    // Checksum (CRC32 of frame data)
    public uint Checksum;

    // Reserved for future use
    private uint _reserved2;

    /// <summary>
    /// Get the size of the frame header in bytes.
    /// </summary>
    public static readonly int Size = Marshal.SizeOf<FrameHeader>();

    /// <summary>
    /// Valid magic number for frame synchronization.
    /// </summary>
    public const uint ValidMagicNumber = 0xAA55AA55;

    /// <summary>
    /// Current protocol version.
    /// </summary>
    public const byte CurrentProtocolVersion = 0x01;

    /// <summary>
    /// Start of frame flag.
    /// </summary>
    public const byte FlagStartOfFrame = 0x01;

    /// <summary>
    /// End of frame flag.
    /// </summary>
    public const byte FlagEndOfFrame = 0x02;

    /// <summary>
    /// Check if this is a start of frame packet.
    /// </summary>
    public readonly bool IsStartOfFrame => (Flags & FlagStartOfFrame) != 0;

    /// <summary>
    /// Check if this is an end of frame packet.
    /// </summary>
    public readonly bool IsEndOfFrame => (Flags & FlagEndOfFrame) != 0;

    /// <summary>
    /// Check if the magic number is valid.
    /// </summary>
    public readonly bool IsValid => MagicNumber == ValidMagicNumber;
}}
";

        await File.WriteAllTextAsync(outputPath, content);
    }

    /// <summary>
    /// Generate all C# SDK files to the specified output directory.
    /// </summary>
    public async Task GenerateAllAsync(DetectorConfig config, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        await GenerateDetectorConfigAsync(config, Path.Combine(outputDir, "DetectorConfig.g.cs"));
        await GenerateFrameHeaderAsync(config, Path.Combine(outputDir, "FrameHeader.g.cs"));
    }
}
