namespace CodeGenerator.Core.Generators;

using System;
using System.IO;
using System.Threading.Tasks;
using CodeGenerator.Core.Models;

/// <summary>
/// SystemVerilog RTL skeleton generator.
/// Generates panel_scan_fsm.sv and line_buffer.sv with correct parameters.
/// SPEC-TOOLS-001 REQ-TOOLS-010
/// </summary>
public class SystemVerilogGenerator
{
    private const string AutoGenHeader = "// AUTO-GENERATED - DO NOT EDIT";
    private const string AutoGenComment = "// Generated by CodeGenerator CLI tool";

    /// <summary>
    /// Generate panel_scan_fsm.sv with parameterized timing.
    /// </summary>
    public async Task GeneratePanelScanFsmAsync(DetectorConfig config, string outputPath)
    {
        var content = $@"{AutoGenHeader}
{AutoGenComment}
// Source: detector_config.yaml
// Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

module panel_scan_fsm #(
    parameter PANEL_ROWS       = {config.Panel.Rows},
    parameter PANEL_COLS       = {config.Panel.Cols},
    parameter PIXEL_BITS       = {config.Panel.BitDepth},
    parameter GATE_ON_US       = {config.Fpga.Timing.GateOnUs},
    parameter GATE_OFF_US      = {config.Fpga.Timing.GateOffUs},
    parameter ROIC_SETTLE_US   = {config.Fpga.Timing.RoicSettleUs},
    parameter ADC_CONV_US      = {config.Fpga.Timing.AdcConvUs}
)(
    input  logic                   clk,
    input  logic                   rst_n,
    input  logic                   scan_enable,
    output logic                   gate_active,
    output logic                   adc_trigger,
    output logic [(ceil_log2(PANEL_ROWS)-1):0] row_addr,
    output logic [(ceil_log2(PANEL_COLS)-1):0] col_addr
);

    // State machine enumeration
    typedef enum logic [2:0] {{
        IDLE,
        GATE_ON,
        ROIC_SETTLE,
        ADC_CONVERT,
        GATE_OFF,
        LINE_ADVANCE,
        DONE
    }} state_t;

    state_t current_state, next_state;

    // State register
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            current_state <= IDLE;
        end else begin
            current_state <= next_state;
        end
    end

    // Next state logic
    always_comb begin
        next_state = current_state;
        case (current_state)
            IDLE: begin
                if (scan_enable)
                    next_state = GATE_ON;
            end
            GATE_ON: begin
                next_state = ROIC_SETTLE;
            end
            ROIC_SETTLE: begin
                next_state = ADC_CONVERT;
            end
            ADC_CONVERT: begin
                next_state = GATE_OFF;
            end
            GATE_OFF: begin
                next_state = LINE_ADVANCE;
            end
            LINE_ADVANCE: begin
                if (row_addr == PANEL_ROWS - 1)
                    next_state = DONE;
                else
                    next_state = GATE_ON;
            end
            DONE: begin
                if (!scan_enable)
                    next_state = IDLE;
            end
            default: begin
                next_state = IDLE;
            end
        endcase
    end

    // Output logic
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            gate_active  <= 1'b0;
            adc_trigger  <= 1'b0;
            row_addr     <= '0;
            col_addr     <= '0;
        end else begin
            case (current_state)
                GATE_ON: begin
                    gate_active <= 1'b1;
                end
                GATE_OFF: begin
                    gate_active <= 1'b0;
                end
                ADC_CONVERT: begin
                    adc_trigger <= 1'b1;
                end
                LINE_ADVANCE: begin
                    adc_trigger <= 1'b0;
                    if (col_addr == PANEL_COLS - 1) begin
                        col_addr <= '0;
                        row_addr <= row_addr + 1'b1;
                    end else begin
                        col_addr <= col_addr + 1'b1;
                    end
                end
                DONE: begin
                    gate_active <= 1'b0;
                    adc_trigger <= 1'b0;
                    row_addr    <= '0;
                    col_addr    <= '0;
                end
            endcase
        end
    end

    // Ceiling log2 function
    function automatic integer ceil_log2(input integer n);
        integer i;
        begin
            for (i = 0; i < 32; i = i + 1) begin
                if (2**i >= n)
                    return i;
            end
            return 32;
        end
    endfunction

endmodule
";

        await File.WriteAllTextAsync(outputPath, content);
    }

    /// <summary>
    /// Generate line_buffer.sv with correct BRAM sizing.
    /// </summary>
    public async Task GenerateLineBufferAsync(DetectorConfig config, string outputPath)
    {
        var addrWidth = CeilLog2(config.Panel.Cols);
        var dataWidth = config.Fpga.LineBuffer.BramWidthBits;
        var depth = config.Fpga.LineBuffer.DepthLines;

        var content = $@"{AutoGenHeader}
{AutoGenComment}
// Source: detector_config.yaml
// Timestamp: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC

module line_buffer #(
    parameter PANEL_COLS       = {config.Panel.Cols},
    parameter DEPTH_LINES      = {depth},
    parameter DATA_WIDTH_BITS  = {dataWidth},
    parameter ADDR_WIDTH       = {addrWidth}
)(
    input  logic                   clk,
    input  logic                   rst_n,
    input  logic                   write_enable,
    input  logic                   read_enable,
    input  logic [(ADDR_WIDTH-1):0] write_addr,
    input  logic [(ADDR_WIDTH-1):0] read_addr,
    input  logic [(DATA_WIDTH_BITS-1):0] write_data,
    output logic [(DATA_WIDTH_BITS-1):0] read_data
);

    // Memory array for ping-pong buffering
    logic [(DATA_WIDTH_BITS-1):0] mem [0:(DEPTH_LINES * PANEL_COLS - 1)];

    // Write port
    always_ff @(posedge clk) begin
        if (write_enable) begin
            mem[write_addr] <= write_data;
        end
    end

    // Read port
    always_ff @(posedge clk) begin
        if (read_enable) begin
            read_data <= mem[read_addr];
        end
    end

endmodule
";

        await File.WriteAllTextAsync(outputPath, content);
    }

    /// <summary>
    /// Generate all RTL files to the specified output directory.
    /// </summary>
    public async Task GenerateAllAsync(DetectorConfig config, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        await GeneratePanelScanFsmAsync(config, Path.Combine(outputDir, "panel_scan_fsm.sv"));
        await GenerateLineBufferAsync(config, Path.Combine(outputDir, "line_buffer.sv"));
    }

    private static int CeilLog2(int n)
    {
        if (n <= 1) return 0;
        int power = 1;
        int log = 0;
        while (power < n)
        {
            power *= 2;
            log++;
        }
        return log;
    }
}
